#!/bin/bash

# Prompt for file names
echo "Enter the name of the first file:"
read file1

echo "Enter the name of the second file:"
read file2

# Find words in file1 that are not in file2
echo "Words in $file1 but not in $file2:"
grep -oFwvf "$file2" "$file1"

# Find words in file2 that are not in file1
echo "Words in $file2 but not in $file1:"
grep -oFwvf "$file1" "$file2"

